"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from skylight_sdk.types import BaseModel
from typing_extensions import TypedDict


class ActiveOperationResponseTypedDict(TypedDict):
    status: str
    r"""Status of the operation"""
    message: str
    r"""Human-readable status message"""
    state: str
    r"""State of the instance (running, pending, hibernated, terminated)"""
    livestream_url: str
    r"""URL to livestream the instance"""


class ActiveOperationResponse(BaseModel):
    status: str
    r"""Status of the operation"""

    message: str
    r"""Human-readable status message"""

    state: str
    r"""State of the instance (running, pending, hibernated, terminated)"""

    livestream_url: str
    r"""URL to livestream the instance"""
