"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from skylight_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Button(str, Enum):
    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"


class ClickRequestTypedDict(TypedDict):
    x: NotRequired[Nullable[int]]
    y: NotRequired[Nullable[int]]
    button: NotRequired[Button]
    clicks: NotRequired[int]


class ClickRequest(BaseModel):
    x: OptionalNullable[int] = UNSET

    y: OptionalNullable[int] = UNSET

    button: Optional[Button] = Button.LEFT

    clicks: Optional[int] = 1

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["x", "y", "button", "clicks"])
        nullable_fields = set(["x", "y"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
