"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from skylight_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Button(str, Enum):
    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"


class ClickRequestTypedDict(TypedDict):
    x: NotRequired[Nullable[int]]
    y: NotRequired[Nullable[int]]
    button: NotRequired[Button]
    clicks: NotRequired[int]
    interval: NotRequired[Nullable[float]]


class ClickRequest(BaseModel):
    x: OptionalNullable[int] = UNSET

    y: OptionalNullable[int] = UNSET

    button: Optional[Button] = Button.LEFT

    clicks: Optional[int] = 1

    interval: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["x", "y", "button", "clicks", "interval"]
        nullable_fields = ["x", "y", "interval"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
