"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from skylight_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DragRequestButton(str, Enum):
    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"


class DragRequestTypedDict(TypedDict):
    path: List[Dict[str, int]]
    button: NotRequired[DragRequestButton]
    step: NotRequired[Nullable[int]]
    r"""Optional step size for drag movements. If not provided, movement will be continuous."""


class DragRequest(BaseModel):
    path: List[Dict[str, int]]

    button: Optional[DragRequestButton] = DragRequestButton.LEFT

    step: OptionalNullable[int] = UNSET
    r"""Optional step size for drag movements. If not provided, movement will be continuous."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["button", "step"])
        nullable_fields = set(["step"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
