"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from skylight_sdk.models import SkylightError
from skylight_sdk.types import BaseModel
from typing import Optional


class ForbiddenErrorResponseData(BaseModel):
    detail: Optional[str] = "Access forbidden"
    r"""Error message for forbidden access"""


@dataclass(unsafe_hash=True)
class ForbiddenErrorResponse(SkylightError):
    r"""Returned when the request cannot be processed due to authentication or authorization issues"""

    data: ForbiddenErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ForbiddenErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
