"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .packageinstallrequest import PackageInstallRequest, PackageInstallRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class InstallRequestTypedDict(TypedDict):
    instance_id: str
    package_install_request: PackageInstallRequestTypedDict


class InstallRequest(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    package_install_request: Annotated[
        PackageInstallRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
