"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mousemoverequest import MouseMoveRequest, MouseMoveRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class MoveRequestTypedDict(TypedDict):
    instance_id: str
    mouse_move_request: MouseMoveRequestTypedDict


class MoveRequest(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    mouse_move_request: Annotated[
        MouseMoveRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
