"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clauderequest import ClaudeRequest, ClaudeRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class RunRequestTypedDict(TypedDict):
    instance_id: str
    claude_request: ClaudeRequestTypedDict


class RunRequest(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    claude_request: Annotated[
        ClaudeRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
