"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from skylight_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class S3VMUploadRequestTypedDict(TypedDict):
    s3_url: str
    r"""The S3 URL of the file to upload"""
    file_name: str
    r"""Original name of the file"""
    file_type: NotRequired[str]
    r"""MIME type of the file"""
    target_path: NotRequired[str]
    r"""Target path on the VM (defaults to Users/Administrator/Desktop/{file_name})"""


class S3VMUploadRequest(BaseModel):
    s3_url: str
    r"""The S3 URL of the file to upload"""

    file_name: str
    r"""Original name of the file"""

    file_type: Optional[str] = None
    r"""MIME type of the file"""

    target_path: Optional[str] = None
    r"""Target path on the VM (defaults to Users/Administrator/Desktop/{file_name})"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_type", "target_path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
