"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scrollrequest import ScrollRequest, ScrollRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ScrollRequest1TypedDict(TypedDict):
    instance_id: str
    scroll_request: ScrollRequestTypedDict


class ScrollRequest1(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    scroll_request: Annotated[
        ScrollRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
