"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .typerequest import TypeRequest, TypeRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class TypeRequest1TypedDict(TypedDict):
    instance_id: str
    type_request: TypeRequestTypedDict


class TypeRequest1(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    type_request: Annotated[
        TypeRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
