"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .s3vmuploadrequest import S3VMUploadRequest, S3VMUploadRequestTypedDict
from skylight_sdk.types import BaseModel
from skylight_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UploadRequestTypedDict(TypedDict):
    instance_id: str
    s3_vm_upload_request: S3VMUploadRequestTypedDict


class UploadRequest(BaseModel):
    instance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    s3_vm_upload_request: Annotated[
        S3VMUploadRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
