"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from skylight_sdk.types import BaseModel
from typing_extensions import TypedDict


class VMPauseResponseTypedDict(TypedDict):
    status: str
    r"""Status of the VM pause operation"""
    message: str
    r"""Human-readable status message"""


class VMPauseResponse(BaseModel):
    status: str
    r"""Status of the VM pause operation"""

    message: str
    r"""Human-readable status message"""
