"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from skylight_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class VMRequestTypedDict(TypedDict):
    api_key: NotRequired[Nullable[str]]
    r"""Optional API key for authentication"""
    timeout_minutes: NotRequired[Nullable[int]]
    r"""Timeout in minutes before VM auto-termination"""


class VMRequest(BaseModel):
    api_key: OptionalNullable[str] = UNSET
    r"""Optional API key for authentication"""

    timeout_minutes: OptionalNullable[int] = UNSET
    r"""Timeout in minutes before VM auto-termination"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["api_key", "timeout_minutes"]
        nullable_fields = ["api_key", "timeout_minutes"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
