"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from skylight_sdk.models import SkylightError
from skylight_sdk.types import BaseModel
from typing import Optional


class WindowsModelsErrorResponseData(BaseModel):
    detail: str
    r"""Error message describing what went wrong"""


@dataclass(unsafe_hash=True)
class WindowsModelsErrorResponse(SkylightError):
    r"""Standard error response containing details about the error"""

    data: WindowsModelsErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: WindowsModelsErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
