"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "skylight-sdk"
__version__: str = "0.0.3"
__openapi_doc_version__: str = "1.0.1"
__gen_version__: str = "2.566.5"
__user_agent__: str = "speakeasy-sdk/python 0.0.3 2.566.5 1.0.1 skylight-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
